Update README.md
zszazi/Deep-learning-in-cloud pull request #114
Opened 2024-02-27 04:56 UTC by DATAOORTS

Added Dataoorts

2024-02-27 08:38 UTC, InCogNiTo124 requested changes

2024-02-27 08:38 UTC, InCogNiTo124 commented on README.md
> +| [Dataoorts](https://dataoorts.com/) | https://dataoorts.com/ | [pricing :label: Starting at $0.55/hr for 1x A100, $0.69/hr for 1x H100 and $0.88 for 1x GH200](https://dataoorts.com/pricing) | - |
Thank you for the contribution! Since we keep the alphabetical ordering, could you move this below dataiku (line 24)?

2024-02-27 10:28 UTC, DATAOORTS reviewed
Just Update it!

2024-02-27 18:11 UTC, merged

2024-03-02 10:28 UTC, Curlypla commented
The site gives very little confidence, all is empty, I do not say that it is a scam but I don't know if it is a good idea to put it without having proven itself.

2024-03-02 12:07 UTC, InCogNiTo124 commented
Thanks for raising concerns @Curlypla.

I did my research about DATAOORTS. I am not sure what you mean by "all is empty" since they seem to have enough content, but it _did_ strike me how unoptimized their page was (slow loads, broken CSS), and how many typos they have.

That said, I concluded that DATAOORTS is probably a new ML platform startup that tries to obtain their first customers, and _I have nothing against that_. This repo is a list of cloud deep learning platforms, but **not** a curated one. If they truly offer a service that is better than the rest, this will enable them to prove themselves. If they don't, there is a lot of other entries in that list for a user to pick from :))

@zszazi do you have anything to add?

2024-03-02 14:59 UTC, rajat709 commented
Hi @Curlypla , I understand that there is currently limited content. However, I'm highly value your feedback, as it will guide us in adding more relevant material in the future. We believe in the importance of concise and meaningful content over an abundance of words that lack substance. Our primary focus is on prioritizing concepts and solutions that we have been diligently working on for the past five months. After continuous testing, we are now confident in moving forward to production, with regular updates planned.

2024-03-02 15:07 UTC, rajat709 commented
Thank You @InCogNiTo124 / cc @DATAOORTS | We should take note of this!